language: node_js

node_js:
  - "10"
  - "11"

cache:
    directories:
        - "node_modules"

script:
  - npm run lint
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  target-branch: master
  on:
    branch: master