name: my-personal-web
services:
- build_command: yarn build
  environment_slug: node-js
  github:
    branch: master
    deploy_on_push: true
    repo: bervProject/my-personal-web
  name: my-personal-web