version: 2.1
orbs:
  node: circleci/node@4.5.1
jobs:
  test:
    branches:
      ignore:
        - gh-pages
    steps:
      - checkout
      - node/install:
          lts: true
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run lint
          name: Run YARN lint
      - run:
          command: yarn run build
          name: Run YARN build
workflows:
  test_my_app:
    jobs:
      - test
