version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    machine: true
    steps:
      - checkout
      # ... steps for building/testing app ...
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t berviantoleo/my-personal-web:$TAG .     
          # docker login -u $DOCKER_USER -p $DOCKER_PASS         # (4)
          # docker push berviantoleo/flutter-docker:$TAG
