version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run lint
          name: Run YARN lint
      - run:
          command: yarn run build
          name: Run YARN build
workflows:
  test_app:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
