version: 2.1
orbs:
  node: circleci/node@4.5.1
jobs:
  test:
    filters:
      branches:
        only:
          - main
    executor: node/default
    steps:
      - checkout
      - node/install:
          lts: true
          install-npm: false
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run lint
          name: Run YARN lint
      - run:
          command: yarn run build
          name: Run YARN build
