version: 2.1
orbs:
  node: circleci/node@5.1.0
  codecov: codecov/codecov@3.2.3
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '18.17'
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn-berry
          override-ci-command: corepack enable && corepack prepare yarn@stable --activate && yarn --immutable
      - run:
          command: yarn lint
          name: Lint
      - run:
          command: yarn build
          name: Build
      - run:
          command: yarn test:unit --ci --maxWorkers=2
          name: Unit Test
      - codecov/upload
      - store_artifacts:
          path: coverage
      - store_artifacts:
          path: dist
workflows:
  test_app:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
